# Dynamically loads sword abilities
#
# ------------------------------------------------------------------------------
# Format:
# ------------------------------------------------------------------------------
# 'item' (required):
#  NBT of the item used to represent an ability in the crafting menu, the
#  'displayName' and 'description' will be applied to the item and will override
#  existing values
#
#  To easily get the NBT of an item for this, simply hold an item ingame, and do
#  '/itemdata view' then click the text it gives you to copy the NBT data, and
#  voila! That's the NBT to use. Be aware! You will need to ensure no string
#  escaping ocurrs with that NBT though.
#
# examples:
# - item = "{id:'minecraft:ender_pearl',Count:1b}"
# ------------------------------------------------------------------------------
# 'recipe' (required):
#  An array of item NBTs. These items are required to craft the ability and then
#  apply it onto a sword
#
#  Please see the previous 'item' section for how to easily get NBT data for
#  items
#
# examples:
# - recipe = [ "{id:'mincraft:ender_pearl',Count:1b}" ]
# - recipe = [
#     "{id:'mincraft:ender_pearl',Count:1b}",
#     "{id:'mincraft:stone_pickaxe',Count:1b}"
#   ]
# ------------------------------------------------------------------------------
# 'displayName' (required):
#  The display name shown to users
#
# examples:
# - displayName = "&eA Display Name"
# - displayName = { text = "A JSON component", color = "red" }
# - displayName = "A colorless display name"
# ------------------------------------------------------------------------------
# 'description' (optional):
#  An array of text shown in the displayName's hover text
#
# examples:
# - description = [ "Foo", "Bar" ]
# - description = [
#     { text = "JSON-style component" },
#     "Regular text"
#   ]
# ------------------------------------------------------------------------------
# 'maxLevel' (required, if 'genericMaxLevel' is not set):
#  Determines the maximum level a sword ability can have.
#  Abilities cannot be levelled past this maxLevel
#
# examples:
# - maxLevel = 5
# ------------------------------------------------------------------------------
# baseCooldown (required, if 'genericBaseCooldown' is not set):
#  The base cooldown, in ticks, the ability has. This base is scaled with the
#  level, the scaling formula is thus:
#  cooldown = base * ( SwordAbility.cooldownScalar / abilityLevel )
#  This decreases cooldown as level increases
#
#  The input for this value can be an integer, which is used as ticks, or a
#  string in the same style as the time argument in commands, eg: '10m' for
#  10 minutes.
#  A comma-separated list of these values is also accepted
#  Lastly, a 'localTime' string is also accepted, see examples, for how to
#  use it.
#
# examples:
# - baseCooldown = 60
#   ^ 3 Seconds, counted as ticks
#
# - baseCooldown = "300t"
#   ^ 300 ticks
#
# - baseCooldown = "10s"
#   ^ 10 seconds
#
# - baseCooldown = "10m, 10s"
#   ^ 10 minutes and 10 seconds
#
# - baseCooldown = 00:00:03
#   ^ 3 Seconds, localTime syntax
# ------------------------------------------------------------------------------
# 'inputArgs' (optional):
#  Optional args to be given to the 'script' value
#
# examples:
# - inputArgs = [ "foo" ]
# - inputArgs = [ "foo", "bar" ]
# - inputArgs = "-foo --foobar=value"
#   ^ Will be split into a string[]
# ------------------------------------------------------------------------------
# 'script' (required):
#  Specifies the script file/JavaScript code to compile and evaluate.
#  The script's main scope will be ran when it's started.
#
#  See the `Script parameters and functions` section for additional details
#  about how this script works
#
# examples:
# - script = "script/path.js"
# - script = { path = "path/to/script.js" }
# - script = { js = "print("Hello, world!")" }
# ------------------------------------------------------------------------------
# 'condition' (optional):
#  If a string, assumes input is raw JavaScript, else you can specify if it's a
#  script path, or a JavaScript code. This value is optional, if not set,
#  condition will always be true.
#
#  The objects placed into the script's bindings are:
#  - user: the user being tested
#  - Permissions: Auto-Import of 'net.forthecrown.core.Permissions'
#
# examples:
# - condition = "user.getGuild() != null"
# - condition = { path = "path/to/script.js" }
# - condition = { js = "false == false" }
# ------------------------------------------------------------------------------
# Script parameters and functions:
# ------------------------------------------------------------------------------
# args: binding object, the String[] of arguments supplied by 'inputArgs'
#       value in this file
#
# type: binding object, the WeaponAbilityType of the current ability instance
#
# level: binding object, the ability's current level
#
# onLeftClick(player, clicked): (optional, if onRightClick is declared)
#  Called when the sword holder (player) left clicks.
#  As such, the 'clicked' parameter, may be an entity, block or null
#
# onRightClick(player, entity): (optional, if onLeftClick is declared)
#  Called when the sword holder (player) right clicks.
#  As such, the 'clicked' parameter, may be an entity, block or null
#
# onLoad(compoundTag): (optional)
#  Called when the ability is loaded, optional function
#
# onSave(compoundTag): (optional)
#  Called when the ability is saved, optional function
#
# getCooldown(): (optional)
#  Called to get a cooldown, optional function
#  If this function isn't declared, uses the baseCooldown and scales it
#  to get a cooldown.
#  This method is allowed to return the same types as the 'baseCooldown' value
#  in this file.
#
# displayName(): (optional)
#  Called to create the ability's displayName, if not declared, uses the
#  'displayName' set in this TOML file.
# ------------------------------------------------------------------------------

# ------------------------------------------------------------------------------
# Example ability:
# ------------------------------------------------------------------------------
# [ability_name]
# displayName = "Weapon Ability"
# description = [ "Does a thing" ]
# maxLevel = 3
# baseCooldown = 00:00:05
# item = "{id:'minecraft:stick',Count:32b}"
# recipe = [ "{id:'minecraft:wooden_axe',Count:64b}" ]
# condition = "user.hasPermission(Permissions.ADMIN)"
# script = "abilities/ability_script.js"
# ------------------------------------------------------------------------------


# ------------------------------------------------------------------------------
# Generic values:
# ------------------------------------------------------------------------------
# Determines if abilities are enabled at all, if not set at all, assumes true
# If false, then will only be enabled if the plugin is on 'debug mode'
# If true, abilities are still loaded, their click callbacks are never called
enabled = false

# Max level that applies for all abilities, unless they override it with their
# own max level value
genericMaxLevel = 5

# Base cooldown value that applies to all abilities, unless they override it
# with their own value
genericBaseCooldown = "3s"
# ------------------------------------------------------------------------------


# ------------------------------------------------------------------------------
# Abilities:
# ------------------------------------------------------------------------------
['ender_pearl']
displayName = "Ender Pearl"
description = [ "Throws an Ender Pearl on Right-Click" ]
maxLevel = 3
script = "abilities/ender_pearl.js"
item = "{id:\"minecraft:ender_pearl\",Count:1b}"
recipe = [
  "{id:\"minecraft:ender_pearl\",Count:1b}"
]

["twirl"]
displayName = "Twirl"
description = [ "Damages all entities around you in a swirl" ]
maxLevel = 3
script = "abilities/twirl.js"
item = "{id:'minecraft:feather',Count:1b}"
recipe = [
  "{id:'minecraft:feather',Count:64b}"
]

["dash"]
displayName = "Dash"
description = [ "Gives you a little boost" ]
script = "abilities/dash.js"
baseCooldown = 00:00:05
item = "{id:'minecraft:iron_boots',Count:1b}"
recipe = [
  "{id:'minecraft:iron_boots',Count:1b}"
]

["far_reach"]
displayName = "Far Reach"
description = [ "Allows you to hit entities up to 5 blocks away" ]
script = "abilities/far_reach.js"
# Each level increases distance
maxLevel = 2
item = "{id:'minecraft:iron_sword',Count:1b}"
recipe = [
  "{id:'minecraft:iron_sword',Count:1b}"
]

# Note on potion types: They don't use the ResourceLocation names, eg:
# 'minecraft:regeneration' for the '--potion-type' values, they use the 'names'
# which are the names of the potion type constants inside the MC codebase, but
# I got tired of over-engineering the potion_effect.js script, so goodluck
["potion/regeneration"]
displayName = "Regeneration"
description = [ "Gives you regen on Right-Click" ]
script = "abilities/potion_effect.js"
inputArgs = "--potion-type=REGENERATION --duration=5s"
item = "{Count:1b,id:'minecraft:potion',tag:{Potion:'minecraft:regeneration'}}"
recipe = [
  "{Count:1b,id:'minecraft:potion',tag:{Potion:'minecraft:regeneration'}}"
]

["potion/strength"]
displayName = "Strength"
description = [ "Gives you Strength on Right-Click" ]
script = "abilities/potion_effect.js"
inputArgs = "--potion-type=INCREASE_DAMAGE --duration=4s"
item = "{Count:1b,id:'minecraft:potion',tag:{Potion:'minecraft:strength'}}"
recipe = [
  "{Count:1b,id:'minecraft:potion',tag:{Potion:'minecraft:strength'}}"
]

["potion/weakness"]
displayName = "Weakness"
description = [ "Gives an enemy weakness on Left-Click" ]
script = "abilities/potion_effect.js"
inputArgs = "--potion-type=WEAKNESS --duration=5s --left-click --give-target"
item = "{Count:1b,id:'minecraft:potion',tag:{Potion:'minecraft:weakness'}}"
recipe = [
  "{Count:1b,id:'minecraft:potion',tag:{Potion:'minecraft:weakness'}}"
]
