# Allows the automatic loading of scripts along with the FTC plugin. Scripts can
# be loaded for a certain period of time, or loaded all the time
# ------------------------------------------------------------------------------
# Format:
# ------------------------------------------------------------------------------
# 'script':
#  Specifies the script file/JavaScript code to compile and evaluate.
#
#  The script's main scope will be ran when it's started.
#
#  If the script has a '__onDayChange' function declared, it will be called when
#  the day resets.
#
# examples:
# - script = "script/path.js"
# - script = { path = "path/to/script.js" }
# - script = { js = "print("Hello, world!")" }
# ------------------------------------------------------------------------------
# 'period':
#  Specifies the range of dates a script will be active for. If not set, a
#  script will always be active
#
# examples:
# - period = "01.01"
#  Only active on the first day of January
#
# - period = [ "01.01", "30.01" ]
#  Active from the 1st till the 30th of January
#
# - period = [ "01.12", "31.01" ]
#  Active from the 1st of December till the 31st of January
# ------------------------------------------------------------------------------
# 'args':
#  A string array of arguments that will be placed into a script's bindings
#  under the name 'inputs' This binding can be accessed like any other array
#
# Declaration examples:
# - args = [ "foo", "bar" ]
# - args = [ "foo" ]
#
# Script examples:
# - 'let value = args[0];'
# - 'if (args.length < 2) throw "Expected 2 arguments";'
# ------------------------------------------------------------------------------

["challenges/top_streak_stand"]
script = "top_streak.js"

["challenges/streak_leaderboard"]
script = "streak_leaderboard.js"

["top_voter_leaderboard"]
script = "top_voters.js"

["raid_village"]
script = "raid_village/main.js"

["rw_reset_counter"]
script = "rw_reset_counter.js"