# -----------------------------------------------------------------------------
# Format
# -----------------------------------------------------------------------------
# interval: (required value)
#  Determines the interval in which the world is reset
#
#  Possible time units:
#  - 'ms' Millisecond
#  - 's' Second
#  - 'm' Minute
#  - 'h' Hour
#  - 'd' Day
#  - 'w' Week
#  - 'mo' Month (28 days)
#  - 'yr' Year (365 days)
#
#  Examples:
#  - 'interval = "1d"' Will reset every day
#  - 'interval = "30d"' Will reset every 30 days
# -----------------------------------------------------------------------------
# seed: (optional value)
#  Sets the seed the world will use when resetting.
#
#  Note: if the "generated_by:<plugin name>" value is used and either the
#  plugin is not found, or the plugin has no SeedGenerator service available,
#  then the system will fall back to the value under the 'plugin_seed_fallback'
#  value
#
#  If this value is unset, defaults to "random"
#
#  Possible values:
#  - "random": Randomizes seed everytime the world is reset
#  - "keep": World seed is unchanged between resets
#  - "generated_by:<plugin name>" Generated by a plugin with a SeedGenerator
#     service
#  - Any number: Becomes the seed
#  - An array of numbers: Seed is chosen randomly
#  - Any other value will just be turned into the seed via java's hashCode()
#    method
#
#  Examples:
#  - 'seed = "random"'
#  - 'seed = "asdwawd"'
#  - 'seed = 598746546548'
#  - 'seed = "generated_by:FTC-ResourceWorld"'
# -----------------------------------------------------------------------------
# pregen_area: (optional value)
#  Sets the area that will be pregenerated after the world is reset. If the
#  value is 'world_border' the entire area inside the world border will be
#  pre-generated. If set to 'none' nothing will be pre-generated.
#
#  The value can also be an object which states the center and radius of the
#  area that will be pre-generated
#
#  If this value is unset, defaults to no pre-generation
#
#  Examples:
#  - 'pregen_area = "world_border"'
#  - 'pregen_area = "none"'
#  - 'pregen_area = { centerX = 0, centerY = 0, radius = 1000 }'
#  - 'pregen_area = { centerX = 0, centerY = 0, radiusX = 1000, radiusY = 2000 }'
# -----------------------------------------------------------------------------

plugin_seed_fallback = "random"

[world_the_end]
interval = "2mo"
seed = "random"
pregen_area = "world_border"

[world_resource]
interval = "1w"
seed = "generated_by:FTC-ResourceWorld"
pregen_area = "world_border"
