[item_head]
description = [
  "&7Willhelm perished in an attack on Questmoor.",
  "&7However, the business of selling heads is",
  "&7still alive and well"
]
slot = 20
reward = { rhines = 100 }

[item_item]
slot = 22

[item_potion]
slot = 24